---
apiVersion: v1
items:
- apiVersion: v1
  data:
    redis.conf: |
      cluster-enabled yes
      cluster-require-full-coverage no
      cluster-node-timeout 15000
      cluster-config-file /data/nodes.conf
      cluster-migration-barrier 1
      appendonly yes
      protected-mode no
  kind: ConfigMap
  metadata:
    creationTimestamp: '2018-08-08T05:54:30Z'
    labels:
      app: redis-cluster
    name: redis-cluster
    namespace: test
    resourceVersion: '15373575'
    selfLink: "/api/v1/namespaces/default/configmaps/redis-cluster"
    uid: 848a6aa4-9acf-11e8-8c8b-42010a8000a2
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: '2018-08-08T05:54:14Z'
    labels:
      app: redis-cluster
    name: redis-cluster
    namespace: test
    resourceVersion: '15373525'
    selfLink: "/api/v1/namespaces/default/services/redis-cluster"
    uid: 7af01238-9acf-11e8-8c8b-42010a8000a2
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - name: http
      nodePort: 30080
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      app: redis-cluster
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    creationTimestamp: '2018-08-08T05:54:31Z'
    generation: 1
    labels:
      app: redis-cluster
    name: redis-cluster
    namespace: test
    resourceVersion: '24073215'
    selfLink: "/apis/apps/v1/namespaces/default/statefulsets/redis-cluster"
    uid: 851a20c6-9acf-11e8-8c8b-42010a8000a2
  spec:
    podManagementPolicy: OrderedReady
    replicas: 6
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: redis-cluster
    serviceName: redis-cluster
    template:
      metadata:
        creationTimestamp:
        labels:
          app: redis-cluster
      spec:
        containers:
        - args:
          - "/conf/redis.conf"
          command:
          - redis-server
          image: amydocker/redis-cluster:v1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - sh
              - "-c"
              - redis-cli -h $(hostname) ping
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          name: redis-cluster
          ports:
          - containerPort: 6379
            name: client
            protocol: TCP
          - containerPort: 16379
            name: gossip
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - sh
              - "-c"
              - redis-cli -h $(hostname) ping
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: '1'
              memory: 4Gi
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: "/conf"
            name: conf
          - mountPath: "/data"
            name: data
        - env:
          - name: SENTINEL
            value: 'true'
          image: kubernetes/redis:v1
          imagePullPolicy: IfNotPresent
          name: sentinel
          ports:
          - containerPort: 26379
            protocol: TCP
          resources: {}
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            items:
            - key: redis.conf
              path: redis.conf
            name: redis-cluster
          name: conf
    updateStrategy:
      type: OnDelete
    volumeClaimTemplates:
    - metadata:
        annotations:
          volume.alpha.kubernetes.io/storage-class: anything
        creationTimestamp:
        labels:
          name: redis-cluster
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
      status:
        phase: Pending
  status:
    collisionCount: 0
    currentReplicas: 6
    currentRevision: redis-cluster-56b6fdddf7
    observedGeneration: 1
    readyReplicas: 6
    replicas: 6
    updateRevision: redis-cluster-56b6fdddf7
kind: List
metadata:
  resourceVersion: ''
  selfLink: ''


